#!/usr/bin/env python3
"""Conservative error-driven function merger for Hybrid Heaven N64Recomp syms.

Only fixes FATAL errors:
  - "Unhandled branch in FUN_X at 0x... to 0xT"   (same-function branch that crossed a split)
Merges the containing function A with the function B containing the target T
(only when both are in the same section). [Warn] branching-outside lines are
ignored: they are non-fatal.

Never merges across sections (.entry vs .main).
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CFG = "game.toml"
SYMS = "us_dec.syms.toml"
N64RECOMP = "../toolchain/src/N64Recomp/build2/N64Recomp"

def load_sections(path):
    sections = []
    cur = None
    for raw in open(path):
        line = raw.strip()
        if line.startswith("[[section]]"):
            cur = {"name": None, "rom": None, "vram": None, "size": None, "funcs": [], "infunctions": False}
            sections.append(cur)
        elif cur is not None:
            m = re.match(r'name = "([^"]+)"', line)
            if m and cur["name"] is None:
                cur["name"] = m.group(1); continue
            m = re.match(r'rom = (0x[0-9A-Fa-f]+)', line)
            if m and cur["rom"] is None:
                cur["rom"] = int(m.group(1), 16); continue
            m = re.match(r'vram = (0x[0-9A-Fa-f]+)', line)
            if m and cur["vram"] is None:
                cur["vram"] = int(m.group(1), 16); continue
            m = re.match(r'size = (0x[0-9A-Fa-f]+)', line)
            if m and cur["size"] is None:
                cur["size"] = int(m.group(1), 16); continue
            if line == "functions = [":
                cur["infunctions"] = True; continue
            if cur["infunctions"]:
                fm = re.match(r'\{\s*name\s*=\s*"([^"]+)"\s*,\s*vram\s*=\s*(0x[0-9A-Fa-f]+)\s*,\s*size\s*=\s*(0x[0-9A-Fa-f]+)\s*\}', line)
                if fm:
                    cur["funcs"].append([fm.group(1), int(fm.group(2), 16), int(fm.group(3), 16)])
                elif line == "]":
                    cur["infunctions"] = False
    for s in sections:
        s["funcs"].sort(key=lambda e: e[1])
    return sections

def write_sections(sections):
    out = ["# Hybrid Heaven (US) - recompilation symbols, autogenerated from Ghidra.",
           "# .entry: boot/libultra block RAM 0x80000400..0x80001000 <-> ROM 0x1000..0x1C00.",
           "# .main : flat main code RAM 0x80001000..0x800E5F40 <-> ROM 0x1000.. (rom = vram - 0x80000000).",
           ""]
    for sec in sections:
        out.append('[[section]]')
        out.append('name = "%s"' % sec["name"])
        out.append('rom = 0x%08X' % sec["rom"])
        out.append('vram = 0x%08X' % sec["vram"])
        out.append('size = 0x%X' % sec["size"])
        out.append('')
        out.append('functions = [')
        for n, v, s in sec["funcs"]:
            out.append('    { name = "%s", vram = 0x%08X, size = 0x%X },' % (n, v, s))
        out.append(']')
        out.append('')
    open(SYMS, 'w').write("\n".join(out))

def code_region_ends_at(rom, addr, cap=0x4000, max_vram=0x800E5F40):
    """Scan 4-byte words from `addr` for a `jr` terminator (with delay slot).

    Used when a branch targets code that Ghidra failed to turn into a function
    (a truncation). Returns the vram address just past the jr delay slot, or
    None if no terminator is found within `cap` bytes of valid code.
    """
    end = min(addr + cap, max_vram)
    a = addr
    while a + 8 <= end:
        off = a - 0x80000000
        if off < 0 or off + 8 > len(rom):
            break
        w1 = (rom[off] << 24) | (rom[off + 1] << 16) | (rom[off + 2] << 8) | rom[off + 3]
        if (w1 >> 26) == 0 and (w1 & 0x3F) == 0x08:  # jr rs
            return a + 8
        a += 4
    return None


def containing_idx(sec, addr):
    fs = sec["funcs"]
    best = None
    for i, (n, v, s) in enumerate(fs):
        if v <= addr:
            best = i
    if best is None:
        return None
    n, v, s = fs[best]
    if addr < v + s:
        return best
    return None  # in a gap

BOGUS_FIRST_OPS = {0x12, 0x32, 0x36, 0x3A, 0x3E}  # cop2/unused opcodes (data artifacts)

# R-type functs that write their result to rd. A data table hits these with rd==0
# (compilers never write to $zero), which the codegen can't even express (emits "0 = ...").
R_TYPE_WRITE_FUNCTS = {0x00, 0x02, 0x03, 0x04, 0x06, 0x20, 0x21, 0x22, 0x23,
                       0x24, 0x25, 0x26, 0x27, 0x2A, 0x2B}

def bogus_func(rom, v, s):
    """True if the function's first word decodes as cop2/unused opcode or as an
    R-type ALU op writing to $zero (impossible in real MIPS code)."""
    off = v - 0x80000000
    if off < 0 or off + 4 > len(rom):
        return True
    w = (rom[off] << 24) | (rom[off + 1] << 16) | (rom[off + 2] << 8) | rom[off + 3]
    if (w >> 26) in BOGUS_FIRST_OPS:
        return True
    if (w >> 26) == 0:  # SPECIAL
        rd = (w >> 11) & 0x1F
        if rd == 0 and (w & 0x3F) in R_TYPE_WRITE_FUNCTS:
            return True
    return False


def main():
    rom = open(os.path.join(ROOT, "work/roms/us_dec.z64"), "rb").read()
    for iteration in range(10000):
        r = subprocess.run([N64RECOMP, CFG], cwd=".", capture_output=True, text=True)
        err = r.stderr + r.stdout
        hard = []
        for m in re.finditer(r'Unhandled branch in ([\w.]+) at 0x[0-9A-Fa-f]+ to (0x[0-9A-Fa-f]+)', err):
            hard.append(("branch", m.group(1), int(m.group(2), 16)))
        for m in re.finditer(r'No function found for jal target: (0x[0-9A-Fa-f]+)', err):
            hard.append(("jal", None, int(m.group(1), 16)))
        for m in re.finditer(r'Unhandled instruction: ([\w.]+)[\r\n]+Error in recompiling ([\w.]+)', err):
            hard.append(("invalid", m.group(2), m.group(1)))
        for m in re.finditer(r'Unhandled link branch at end of ([\w.]+)', err):
            hard.append(("linkend", m.group(1), None))
        if not hard:
            if "Error recompiling" in err:
                print("STILL FATAL errors (unknown type) at iteration %d" % iteration)
                print([l for l in err.splitlines() if "Error" in l][:10])
                return 1
            print("CLEAN after %d iterations" % iteration)
            return 0
        sections = load_sections(SYMS)
        dropped = 0
        for sec in sections:
            kept = [fn for fn in sec["funcs"] if not bogus_func(rom, fn[1], fn[2])]
            dropped += len(sec["funcs"]) - len(kept)
            sec["funcs"] = kept
        if dropped:
            write_sections(sections)
            print("  iter %d: dropped %d bogus data-artifact functions" % (iteration, dropped))
            continue
        loc = {}
        for si, sec in enumerate(sections):
            for fi, fn in enumerate(sec["funcs"]):
                loc[fn[0]] = (si, fi)
        merges = []
        failed = []
        for kind, fname, taddr in hard:
            if kind == "invalid":
                if fname not in loc:
                    failed.append(("name-not-found", fname)); continue
                si, fi = loc[fname]
                sections[si]["funcs"].pop(fi)
                merges.append(("drop-instr", fname, taddr))
                continue
            if kind == "jal":
                exists = any(sec["funcs"][i][1] == taddr for sec in sections for i in range(len(sec["funcs"])))
                if exists:
                    continue
                failed.append(("jal-nowhere", taddr))
                continue
            if fname not in loc:
                failed.append(("name-not-found", fname)); continue
            si, fi = loc[fname]
            sec = sections[si]
            if kind == "linkend":
                if fi + 1 >= len(sec["funcs"]):
                    failed.append(("linkend-no-next", fname, sec["name"])); continue
                taddr = sec["funcs"][fi + 1][1]
            a_start = sec["funcs"][fi][1]
            a_end = a_start + sec["funcs"][fi][2]
            if a_start <= taddr < a_end:
                continue
            b_idx = containing_idx(sec, taddr)
            if b_idx is None:
                # Target lands in a gap between functions (Ghidra truncation):
                # absorb everything from the current function up to the next
                # function start in the same section.
                nxt = [i for i, (n2, v2, s2) in enumerate(sec["funcs"]) if v2 > taddr]
                if not nxt:
                    failed.append(("branch-nowhere-beyond-last", fname, taddr, sec["name"]))
                    continue
                b_idx = nxt[0]
                if sec["funcs"][b_idx][1] - a_end > 0x800:
                    # Large gap: likely a Ghidra truncation with hidden code that
                    # does not form a function. Extend THIS function through the
                    # code continuation, ending at a `jr` terminator.
                    code_end = code_region_ends_at(rom, taddr)
                    if code_end is None or code_end <= a_end or code_end - a_end > 0x4000:
                        failed.append(("branch-nowhere-big-gap", fname, taddr, sec["name"]))
                        continue
                    code_end = min(code_end, sec["funcs"][b_idx][1])
                    sec["funcs"][fi][2] = code_end - a_start
                    merges.append(("extend", a_start, code_end - a_start))
                    continue
            b_start = sec["funcs"][b_idx][1]
            b_end = b_start + sec["funcs"][b_idx][2]
            new_start = min(a_start, b_start)
            new_end = max(a_end, b_end)
            changed = True
            while changed:
                changed = False
                for n2, v2, s2 in sec["funcs"]:
                    if new_start < v2 and v2 < new_end and (v2 + s2) > new_end:
                        new_end = v2 + s2
                        changed = True
            kept = []
            exact_span = None
            for n2, v2, s2 in sec["funcs"]:
                if new_start <= v2 < new_end:
                    if new_start == v2 and new_end == v2 + s2:
                        exact_span = [n2, v2, s2]
                    continue
                kept.append([n2, v2, s2])
            if exact_span is None:
                merged = ["FUN_%08x" % new_start, new_start, new_end - new_start]
            else:
                # The containing function already spans everything: the merge is a
                # subsumption, so just keep it and drop the now-redundant fragment(s).
                merged = None
            if merged is not None:
                kept.append(merged)
            kept.sort(key=lambda e: e[1])
            # safety: one entry per start address
            dedup = {}
            for e in kept:
                if e[1] not in dedup or e[2] > dedup[e[1]][2]:
                    dedup[e[1]] = e
            sec["funcs"] = sorted(dedup.values(), key=lambda e: e[1])
            merges.append(("merge", new_start, new_end - new_start))
        if failed:
            print("UNRESOLVED issues: %s" % failed[:6])
            return 1
        write_sections(sections)
        print("  iter %d: %d fatal issues -> %d merges" % (iteration, len(hard), len(merges)))
    print("MAX ITERATIONS reached")
    return 1

if __name__ == "__main__":
    sys.exit(main())