# Config file for Hybrid Heaven (USA) flat main-code recompilation (Fase 2).
# ROM: work/roms/us_dec.z64 (plana; código plano = RAM - 0x80000000).

[input]
entrypoint = 0x80000400
output_func_path = "RecompiledFuncs"
relocatable_sections_path = ""
symbols_file_path = "us_dec.syms.toml"
rom_file_path = "../work/roms/us_dec.z64"
use_lookup_for_all_function_calls = true

[patches]
stubs = [
]

ignored = [
]
